DROP TABLE user_roles IF EXISTS;
DROP TABLE meals IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE restaurants IF EXISTS;

/*
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 10000;

CREATE TABLE users
(
    id               BIGINT GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    login             VARCHAR(255)            NOT NULL,
    password         VARCHAR(255)            NOT NULL,
    lastVoteDateTime TIMESTAMP               NOT NULL
);
CREATE UNIQUE INDEX unique_login
    ON USERS (login);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE restaurants
(
    id               BIGINT GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name             VARCHAR(255)            NOT NULL

        FOREIGN KEY (owner_id) REFERENCES RESTAURANTS (id) ON DELETE CASCADE
);

CREATE TABLE meals
(
    id          BIGINT GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price    INT          NOT NULL,
    owner_id     BIGINT      NOT NULL,

);
*/
